esphome:
  name: living_room_ac

esp32:
  board: nodemcu-32s

preferences:
  flash_write_interval: 10min

wifi:
  ssid: !secret ssid  
  password: !secret wappw

# Disable logging over USB
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  password: !secret apipw

ota:
  password: !secret apipw

### BEGIN GOOD STUFF ###

# status_led:
#   pin:
#     inverted: False
#     number: GPIO2

remote_transmitter:
  pin: 
    number: GPIO23
    inverted: false
  carrier_duty_percent: 50%
 
remote_receiver:
 pin: 
   number: GPIO22
   inverted: true
 dump: nec

# UART is used by the pmsx003
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600

sensor:
  - platform: pmsx003
    type: PMSX003
    pm_1_0:
      id: livingroom_air_pm_1um
      name: "Living Room P1.0µm"
    pm_2_5:
      id: livingroom_air_pm_2um
      name: "Living Room P2.5µm"
    pm_10_0:
      id: livingroom_air_pm_10um
      name: "Living Room P10.0µm"
    # Need to merge stable back into climate_ir_insignia to get this option back
    # update_interval: 30000ms
 
climate:
  - platform: whynter
    name: Living Room AC
    # sensor: alpha_den_mobile_temperature
    supports_heat: false
